#!/bin/bash

pushd `dirname $0` > /dev/null
SCRIPTPATH=`pwd -P`
popd > /dev/null

SPLUNKHOME_FILE="$SCRIPTPATH/.splunkhome"

HOMEPATH=`cat $SPLUNKHOME_FILE 2> /dev/null`

if [ "$HOMEPATH" = "" ]
then
    read -e -p "Where is Splunk installed (version 5.0 or later is required)? [$SPLUNK_HOME]: " HOMEPATH
    
    if [ "$HOMEPATH" = "" ]
    then
        if [ "$SPLUNK_HOME" != "" ]
        then
            HOMEPATH=$SPLUNK_HOME
        else
            echo "Must supply a 'SPLUNK_HOME' value"
            exit 1
        fi
    fi
    
    eval HOMEPATH=$HOMEPATH
    if [[ ! -d "$HOMEPATH" ]]
    then
        echo "'$HOMEPATH does not exist. Please provide a valid SPLUNK_HOME value".
        exit 1
    fi
    
    echo $HOMEPATH > "$SCRIPTPATH/.splunkhome"
fi

export SPLUNK_HOME=$HOMEPATH

export PYTHON_HOME=`which python`
# Add the node_modules bin directory to the PATH
export PATH="$SCRIPTPATH/node_modules/.bin:$SPLUNK_HOME/bin:$PATH"

# Add our base Python packages to PYTHONPATH
export PYTHONPATH="$SCRIPTPATH/contrib/splunk-sdk-python:$SCRIPTPATH/contrib/envoy:$SCRIPTPATH/contrib/argh:$SCRIPTPATH/contrib/django:$PYTHONPATH"

# We have to make the contrib/django directory to make sure
# Python sees it in the PYTHONPATH
mkdir -p $SCRIPTPATH/contrib/django

# Run the actual CLI environment
"$SPLUNK_HOME/bin/splunk" cmd python "$SCRIPTPATH/cli/appdo.py" $@
